import dataclasses
from typing import ClassVar
import einops
import numpy as np
from openpi import transforms
from openpi.models import model as _model


@dataclasses.dataclass(frozen=True)
class KoboInputs(transforms.DataTransformFn):
    model_type: _model.ModelType

    def __call__(self, data: dict) -> dict:
        # 1. Parse and format the single camera frame
        in_images = data["image"]
        if isinstance(in_images, dict):
            raw_img = in_images["observation.image.cam1"]
        else:
            raw_img = in_images
            
        raw_img = np.asarray(raw_img)
        if np.issubdtype(raw_img.dtype, np.floating):
            raw_img = (255 * raw_img).astype(np.uint8)
            
        img_hwc = einops.rearrange(raw_img, "c h w -> h w c")

        # 2. Replicate Libero's exact top-level layout structural signatures
        inputs = {
            "state": np.asarray(data["state"], dtype=np.float32),
            "image": {
                "base_0_rgb": img_hwc,
                # Libero fills missing cameras with zeros; we match that convention here
                "left_wrist_0_rgb": np.zeros_like(img_hwc),
                "right_wrist_0_rgb": np.zeros_like(img_hwc),
            },
            "image_mask": {
                "base_0_rgb": np.True_,
                "left_wrist_0_rgb": np.True_ if self.model_type == _model.ModelType.PI0_FAST else np.False_,
                "right_wrist_0_rgb": np.True_ if self.model_type == _model.ModelType.PI0_FAST else np.False_,
            },
        }

        # 3. Handle actions and prompt pass-through sequences flatly
        if "actions" in data:
            inputs["actions"] = np.asarray(data["actions"], dtype=np.float32)

        if "prompt" in data:
            inputs["prompt"] = data["prompt"]

        return inputs


@dataclasses.dataclass(frozen=True)
class KoboOutputs(transforms.DataTransformFn):
    """Outputs for the Kobo policy."""

    def __call__(self, data: dict) -> dict:
        # Simply return the action sequence matrix generated by the neural network layers.
        # Since your target coordinates match your tracking space precisely, 
        # no inverted math functions or mirror modifications are needed here.
        return {"actions": np.asarray(data["actions"], dtype=np.float32)}